apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    steps:
      - uses: gradinsky-cloudbees/example-action@v1.0.0
        name: custom
        id: custom-action
        with:
          url: https://cloudbees.com

